### ISSUE TITLE
"teams_content_mode" should be "teams_message_type" on README.md

### ISSUE THREAD

**Issue by bsdmad** [danieltoader/capistrano-teams#3]
Thanks for your plugin!

README.md tells us that we can use "teams_content_mode" for selection for message type - Message::TYPE_BASIC or Message::TYPE_CARD, but it doesn't work even if we set it to  "Message::TYPE_CARD" and it is always setted as "Message::TYPE_BASIC" which is default.

I got to know that the parameter "teams_content_mode" should be "teams_message_type" after reading your code.  Please check it :)

**Comment by danieltoader** [comment]
Thank you for the comment, sorry for the very long wait. I fixed the documentation. Any future improvement proposals are greatly appreciated.
